### ISSUE TITLE
Incompatible character encodings: UTF-8 and ASCII-8BIT 

### ISSUE THREAD

**Issue by talsafran** [github/email_reply_parser#10]
I'm getting an `incompatible character encodings: UTF-8 and ASCII-8BIT` error using `parse_reply` in a Rails view on certain strings.

I admittedly do not know much about encoding... so I spent a bunch of time googling but to no avail.

Here's an example of one offending string. I don't see anything wrong with it and hope Github isn't sanitizing any of it when I paste it in. But why not...

    Hi Jaime,  This just came in last night from the local Nantucket dive shop I contacted: \"We do lobster diving charters all the time in August- just call or pop in at least a week in advance and talk to Phil Sr.  Thanks,  The Sunken Ship crew\"  If you'd like us to book something on your behalf, let me know, otherwise contact info is:  [omitted]  Thanks!  Rachel   On June 6 @ 01:19 PM, [omitted] wrote: Hey Jamie!  Here is Mike's info: [omitted]     

I'm getting these strings from my database which is UTF-8. I've tried to use `force_encoding` and still get the error. Any clues? Am I not doing something foolishly obvious?

**Comment by summera** [comment]
@rymohr @technoweenie Ran into this as well. Put in a PR https://github.com/github/email_reply_parser/pull/36

**Comment by rymohr** [comment]
Thanks @summera.  We're still running into this occasionally and haven't found a proper fix for it yet.  I'll take a look at the changes you made in the PR.

Any idea what the original benefit of working with raw bytes was?  https://github.com/github/email_reply_parser/pull/36/files#diff-240c7196a90b5bff539340e9dbb77926L79

**Comment by summera** [comment]
@rymohr I'm not exactly sure to be honest. This article might help you if you are still running into the problem:

http://robots.thoughtbot.com/fight-back-utf-8-invalid-byte-sequences

**Comment by fiedl** [comment]
Same issue here with version 0.5.8.

### Fix

Good news: This gets fixed with https://github.com/github/email_reply_parser/pull/51, which has already [been merged](https://github.com/github/email_reply_parser/commit/d0fe3778b2836ded6b1b1a6d99bc4af9b62785e8).

Bad news: It's not released, yet.

@tenderlove. Could you release v0.5.9 for us? Thanks!

### Workaround

Until v0.5.9 is released, there are a couple of workarounds:

1. Either, specify the `master` branch of this repo in your `Gemfile`:
  
  ```ruby
  # Gemfile
  
  gem 'email_reply_parser', github: 'github/email_reply_parser'
  ```

2. Or, if you can't do this for some reason, e.g. because you are working on a gem yourself (i.e. you have a `*gemspec` rather than a `Gemfile`), you could go boldly forth and patch `String` to ignore the forced binary encoding :-)

  ```ruby
  # lib/core_ext/string.rb
  
  module StringPatches
    def force_encoding(encoding_type)
      # TODO: Remove this hack after
      #
      #    https://github.com/github/email_reply_parser/commit/d0fe3778b2836ded6b1b1a6d99bc4af9b62785e8
      #
      # i.e. email_reply_parser 0.5.9 is released.
      #
      if encoding_type == 'binary'
        return self
      else
        return super
      end
    end
  end
  
  class String
    prepend StringPatches
  end
  ```

(Don't forget to `require lib/core_ext/string`.)

**Comment by tenderlove** [comment]
> @tenderlove. Could you release v0.5.9 for us? Thanks!

Done!  I'll close this ticket now.

Thank you!

**Comment by fiedl** [comment]
@tenderlove : Great, it works, thanks!
